import 'dart:convert';
import 'package:equatable/equatable.dart';

class WoTestParameterModel extends Equatable {
  final int? id, harga, log, externalLabHarga, samplingWoId, hasilIsdone, isReceived, quotationId, samplepengujianId, parameterUjiId, metodaId, personilId, bakumutuId, batchId;
  final num? hasilSimplo, hasilDuplo, hasilRataan, hasilRdp, hasilPetugasId;
  final bool? externalLab, batchAnalysis, checkedKualitatif, checkedPengukuranSesaat, checkedPengukuranFlowActual;
  final String? samplepengujianBakumutuId, parameteruji, metoda, alatUtama, statusAlat, personil, kondisiAkomodasi, statusReagen, satuan, overload, akreditasi, kodeWadahSample, wadah, volume, pengawetan, batasPenyimpanan, externalLabName, dataTaken, caraPengambilan, larutanPenjerap, hasilPengujian, hasilWaktuPengukuran, hasilWaktuPengukuranAkhir, hasilWaktuKirim, hasilStatusVerifikasi, hasilWaktuVerifikasi, hasilPetugasNama, hasilWaktuSampling, hasilCatatanPengambilan, hasilPengujianKualitatif, catatanPengujianKualitatif, pengukuranFlowActual;
  final List<WoTestParameterModel>? list;

  const WoTestParameterModel({
    this.id,
    this.harga,
    this.log,
    this.externalLabHarga,
    this.samplingWoId,
    this.hasilSimplo,
    this.hasilDuplo,
    this.hasilRataan,
    this.hasilRdp,
    this.hasilPetugasId,
    this.hasilIsdone,
    this.isReceived,
    this.quotationId,
    this.samplepengujianId,
    this.parameterUjiId,
    this.metodaId,
    this.personilId,
    this.bakumutuId,
    this.batchId,
    this.samplepengujianBakumutuId,
    this.parameteruji,
    this.metoda,
    this.alatUtama,
    this.statusAlat,
    this.personil,
    this.kondisiAkomodasi,
    this.statusReagen,
    this.satuan,
    this.overload,
    this.akreditasi,
    this.kodeWadahSample,
    this.wadah,
    this.volume,
    this.pengawetan,
    this.batasPenyimpanan,
    this.externalLabName,
    this.dataTaken,
    this.caraPengambilan,
    this.larutanPenjerap,
    this.hasilPengujian,
    this.hasilWaktuPengukuran,
    this.hasilWaktuPengukuranAkhir,
    this.hasilWaktuKirim,
    this.hasilStatusVerifikasi,
    this.hasilWaktuVerifikasi,
    this.hasilPetugasNama,
    this.hasilWaktuSampling,
    this.hasilCatatanPengambilan,
    this.hasilPengujianKualitatif,
    this.catatanPengujianKualitatif,
    this.externalLab,
    this.batchAnalysis,
    this.checkedKualitatif,
    this.checkedPengukuranSesaat,
    this.checkedPengukuranFlowActual,
    this.pengukuranFlowActual,
    this.list
  });

  @override
  List<Object?> get props => [
    id,
    harga,
    log,
    externalLabHarga,
    samplingWoId,
    hasilSimplo,
    hasilDuplo,
    hasilRataan,
    hasilRdp,
    hasilPetugasId,
    hasilIsdone,
    isReceived,
    quotationId,
    samplepengujianId,
    parameterUjiId,
    metodaId,
    personilId,
    bakumutuId,
    batchId,
    externalLab,
    batchAnalysis,
    checkedKualitatif,
    checkedPengukuranSesaat,
    checkedPengukuranFlowActual,
    samplepengujianBakumutuId,
    parameteruji,
    metoda,
    alatUtama,
    statusAlat,
    personil,
    kondisiAkomodasi,
    statusReagen,
    satuan,
    overload,
    akreditasi,
    kodeWadahSample,
    wadah,
    volume,
    pengawetan,
    batasPenyimpanan,
    externalLabName,
    dataTaken,
    caraPengambilan,
    larutanPenjerap,
    hasilPengujian,
    hasilWaktuPengukuran,
    hasilWaktuPengukuranAkhir,
    hasilWaktuKirim,
    hasilStatusVerifikasi,
    hasilWaktuVerifikasi,
    hasilPetugasNama,
    hasilWaktuSampling,
    hasilCatatanPengambilan,
    hasilPengujianKualitatif,
    catatanPengujianKualitatif,
    pengukuranFlowActual,
    list
  ];

  WoTestParameterModel copyWith({
    int? id, harga, log, externalLabHarga, samplingWoId, hasilIsdone, isReceived, quotationId, samplepengujianId, parameterUjiId, metodaId, personilId, bakumutuId, batchId,
    num? hasilSimplo, hasilDuplo, hasilRataan, hasilRdp, hasilPetugasId,
    bool? externalLab, batchAnalysis, checkedKualitatif, checkedPengukuranSesaat, checkedPengukuranFlowActual,
String? samplepengujianBakumutuId, parameteruji, metoda, alatUtama, statusAlat, personil, kondisiAkomodasi, statusReagen, satuan, overload, akreditasi, kodeWadahSample, wadah, volume, pengawetan, batasPenyimpanan, externalLabName, dataTaken, caraPengambilan, larutanPenjerap, hasilPengujian, hasilWaktuPengukuran, hasilWaktuPengukuranAkhir, hasilWaktuKirim, hasilStatusVerifikasi, hasilWaktuVerifikasi, hasilPetugasNama, hasilWaktuSampling, hasilCatatanPengambilan, hasilPengujianKualitatif, catatanPengujianKualitatif, pengukuranFlowActual,
    List<WoTestParameterModel>? list
  }) => WoTestParameterModel(
    id: id ?? this.id,
    harga: harga ?? this.harga,
    log: log ?? this.log,
    externalLabHarga: externalLabHarga ?? this.externalLabHarga,
    samplingWoId: samplingWoId ?? this.samplingWoId,
    hasilSimplo: hasilSimplo ?? this.hasilSimplo,
    hasilDuplo: hasilDuplo ?? this.hasilDuplo,
    hasilRataan: hasilRataan ?? this.hasilRataan,
    hasilRdp: hasilRdp ?? this.hasilRdp,
    hasilPetugasId: hasilPetugasId ?? this.hasilPetugasId,
    hasilIsdone: hasilIsdone ?? this.hasilIsdone,
    isReceived: isReceived ?? this.isReceived,
    quotationId: quotationId ?? this.quotationId,
    samplepengujianId: samplepengujianId ?? this.samplepengujianId,
    parameterUjiId: parameterUjiId ?? this.parameterUjiId,
    metodaId: metodaId ?? this.metodaId,
    personilId: personilId ?? this.personilId,
    bakumutuId: bakumutuId ?? this.bakumutuId,
    batchId: batchId ?? this.batchId,
    externalLab: externalLab ?? this.externalLab,
    batchAnalysis: batchAnalysis ?? this.batchAnalysis,
    checkedKualitatif: checkedKualitatif ?? this.checkedKualitatif,
    checkedPengukuranSesaat: checkedPengukuranSesaat ?? this.checkedPengukuranSesaat,
    checkedPengukuranFlowActual: checkedPengukuranFlowActual ?? this.checkedPengukuranFlowActual,
    samplepengujianBakumutuId: samplepengujianBakumutuId ?? this.samplepengujianBakumutuId,
    parameteruji: parameteruji ?? this.parameteruji,
    metoda: metoda ?? this.metoda,
    alatUtama: alatUtama ?? this.alatUtama,
    statusAlat: statusAlat ?? this.statusAlat,
    personil: personil ?? this.personil,
    kondisiAkomodasi: kondisiAkomodasi ?? this.kondisiAkomodasi,
    statusReagen: statusReagen ?? this.statusReagen,
    satuan: satuan ?? this.satuan,
    overload: overload ?? this.overload,
    akreditasi: akreditasi ?? this.akreditasi,
    kodeWadahSample: kodeWadahSample ?? this.kodeWadahSample,
    wadah: wadah ?? this.wadah,
    volume: volume ?? this.volume,
    pengawetan: pengawetan ?? this.pengawetan,
    batasPenyimpanan: batasPenyimpanan ?? this.batasPenyimpanan,
    externalLabName: externalLabName ?? this.externalLabName,
    dataTaken: dataTaken ?? this.dataTaken,
    caraPengambilan: caraPengambilan ?? this.caraPengambilan,
    larutanPenjerap: larutanPenjerap ?? this.larutanPenjerap,
    hasilPengujian: hasilPengujian ?? this.hasilPengujian,
    hasilWaktuPengukuran: hasilWaktuPengukuran ?? this.hasilWaktuPengukuran,
    hasilWaktuPengukuranAkhir: hasilWaktuPengukuranAkhir ?? this.hasilWaktuPengukuranAkhir,
    hasilWaktuKirim: hasilWaktuKirim ?? this.hasilWaktuKirim,
    hasilStatusVerifikasi: hasilStatusVerifikasi ?? this.hasilStatusVerifikasi,
    hasilWaktuVerifikasi: hasilWaktuVerifikasi ?? this.hasilWaktuVerifikasi,
    hasilPetugasNama: hasilPetugasNama ?? this.hasilPetugasNama,
    hasilWaktuSampling: hasilWaktuSampling ?? this.hasilWaktuSampling,
    hasilCatatanPengambilan: hasilCatatanPengambilan ?? this.hasilCatatanPengambilan,
    hasilPengujianKualitatif: hasilPengujianKualitatif ?? this.hasilPengujianKualitatif,
    catatanPengujianKualitatif: catatanPengujianKualitatif ?? this.catatanPengujianKualitatif,
    pengukuranFlowActual: pengukuranFlowActual ?? this.pengukuranFlowActual,
    list: list ?? this.list
  );

  factory WoTestParameterModel.fromMap(Map<String, dynamic> m) => WoTestParameterModel(
    id: m['id'] ?? 0,
    harga: m['harga'] ?? 0,
    log: m['log'] ?? 0,
    externalLabHarga: m['external_lab_harga'] ?? 0,
    samplingWoId: m['samplingwo_id'] ?? 0,
    hasilSimplo: m['hasil_simplo'] ?? 0.0,
    hasilDuplo: m['hasil_duplo'] ?? 0.0,
    hasilRataan: m['hasil_rataan'] ?? 0.0,
    hasilRdp: m['hasil_rdp'] ?? 0.0,
    hasilPetugasId: m['hasil_petugas_id'] ?? 0.0,
    hasilIsdone: m['hasil_isdone'] ?? 0,
    isReceived: m['is_received'] ?? 0,
    quotationId: m['quotation_id'] ?? 0,
    samplepengujianId: m['samplepengujian_id'] ?? 0,
    parameterUjiId: m['parameter_uji_id'] ?? 0,
    metodaId: m['metoda_id'] ?? 0,
    personilId: m['personil_id'] ?? 0,
    bakumutuId: m['bakumutu_d'] ?? 0,
    batchId: m['batch_d'] ?? 0,
    /*externalLab: m['external_lab'] ?? 0,
    checkedKualitatif: m['checked_kualitatif'] ?? 0,
    batchAnalysis: m['batch_analysis'] ?? 0,
    checkedPengukuranSesaat: m['checked_pengukuran_sesaat'] ?? 0,
    checkedPengukuranFlowActual: m['checked_pengukuran_flow_actual'] ?? false,*/
    samplepengujianBakumutuId: m['samplepengujian_bakumutu_id'] ?? '',
    parameteruji: m['parameteruji'] ?? '',
    metoda: m['metoda'] ?? '',
    alatUtama: m['alat_utama'] ?? '',
    statusAlat: m['status_alat'] ?? '',
    personil: m['personil'] ?? '',
    kondisiAkomodasi: m['kondisi_akomodasi'] ?? '',
    statusReagen: m['status_reagen'] ?? '',
    satuan: m['satuan'] ?? '',
    overload: m['overload'] ?? '',
    akreditasi: m['akreditasi'] ?? '',
    kodeWadahSample: m['kode_wadah_sample'] ?? '',
    wadah: m['wadah'] ?? '',
    volume: m['volume'] ?? '',
    pengawetan: m['pengawetan'] ?? '',
    batasPenyimpanan: m['batas_penyimpanan'] ?? '',
    externalLabName: m['external_lab_name'] ?? '',
    dataTaken: m['data_taken'] ?? '',
    caraPengambilan: m['cara_pengambilan'] ?? '',
    larutanPenjerap: m['larutan_penjerap'] ?? '',
    hasilPengujian: m['hasil_pengujian'] ?? '',
    hasilWaktuPengukuran: m['hasil_waktu_pengukuran'] ?? '',
    hasilWaktuPengukuranAkhir: m['hasil_waktu_pengukuran_akhir'] ?? '',
    hasilWaktuKirim: m['hasil_waktu_kirim'] ?? '',
    hasilStatusVerifikasi: m['hasil_status_verifikasi'] ?? '',
    hasilWaktuVerifikasi: m['hasil_waktu_verifikasi'] ?? '',
    hasilPetugasNama: m['hasil_petugas_nama'] ?? '',
    hasilWaktuSampling: m['hasil_waktu_sampling'] ?? '',
    hasilCatatanPengambilan: m['hasil_catatan_pengambilan'] ?? '',
    hasilPengujianKualitatif: m['hasil_pengujian_kualitatif'] ?? '',
    catatanPengujianKualitatif: m['catatan_pengujian_pualitatif'] ?? '',
    pengukuranFlowActual: m['pengukuran_flow_actual'] ?? ''
  );

  factory WoTestParameterModel.fromList(List l) {
    List<WoTestParameterModel> list = [];
    l.map((a) => list.add(WoTestParameterModel.fromMap(a))).toList();
    return WoTestParameterModel(list: list);
  }

  factory WoTestParameterModel.fromString(String s) => WoTestParameterModel.fromMap(jsonDecode(s));
}
